FROM ubuntu:18.10

ENV BASEDIR=/var/qminer

RUN mkdir $BASEDIR

RUN apt-get update \
    && apt-get install -y build-essential curl gdb git liblz4-dev libpq-dev libssl-dev locales python unzip wget zlib1g-dev && locale-gen en_US.UTF-8\
# nodejs
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install -y nodejs \
    && npm install -g node-gyp \
# qminer
    && git clone https://github.com/qminer/qminer.git $BASEDIR/qminer \
    && node-gyp configure build -C $BASEDIR/qminer \
# cleanup
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/*
